# Generated by Django 4.1.1 on 2023-06-25 15:24

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Learning_Module",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("module_title", models.CharField(default="", max_length=50)),
                ("module_description", models.TextField(default="")),
                ("module_tags", models.TextField(default="")),
                (
                    "module_DOR",
                    models.DateTimeField(
                        default=datetime.datetime(2023, 6, 25, 18, 24, 48, 224758)
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Module_Topic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("topic_name", models.CharField(default="", max_length=150)),
                ("topic_description", models.TextField(default="")),
                ("topic_tags", models.TextField(default="")),
                (
                    "module_belongs_to",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="PLCS_system.learning_module",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Permission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("permission_action", models.CharField(default="", max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("project_id", models.CharField(max_length=15)),
                ("project_title", models.CharField(max_length=300)),
                ("project_description", models.TextField()),
                (
                    "project_DOR",
                    models.DateTimeField(
                        default=datetime.datetime(2023, 6, 25, 18, 24, 48, 224758)
                    ),
                ),
                ("project_budget", models.IntegerField(default=1)),
                ("project_skills", models.TextField(default="")),
                ("project_collaborators", models.IntegerField(default=1)),
                ("accepted_project_collaborators", models.IntegerField(default=1)),
                (
                    "project_deadline",
                    models.DateTimeField(
                        default=datetime.datetime(2023, 6, 25, 18, 24, 48, 224758)
                    ),
                ),
                ("project_images", models.TextField(default="")),
                ("project_files", models.TextField(default="")),
                (
                    "last_updated",
                    models.DateTimeField(
                        default=datetime.datetime(2023, 6, 25, 18, 24, 48, 224758)
                    ),
                ),
                ("status", models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name="Role",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("role_name", models.CharField(default="normal user", max_length=15)),
                (
                    "role_description",
                    models.CharField(default="normal user", max_length=150),
                ),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=15)),
                ("last_name", models.CharField(max_length=15)),
                ("email", models.CharField(max_length=45)),
                ("password", models.CharField(max_length=15)),
                ("status", models.IntegerField(default=1)),
                (
                    "date_of_registration",
                    models.DateTimeField(
                        default=datetime.datetime(2023, 6, 25, 18, 24, 48, 224758)
                    ),
                ),
                (
                    "last_login",
                    models.DateTimeField(
                        default=datetime.datetime(2023, 6, 25, 18, 24, 48, 224758)
                    ),
                ),
                ("profile_img", models.TextField(default="")),
                ("learning_interests", models.TextField(default="")),
                ("project_interests", models.TextField(default="")),
                ("user_activity_tags", models.TextField(default="")),
                (
                    "user_description",
                    models.TextField(default="I am a new user to this system"),
                ),
            ],
            options={"db_table": "User",},
        ),
        migrations.CreateModel(
            name="User_Role",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role_x",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="PLCS_system.role",
                    ),
                ),
                (
                    "user_x",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="PLCS_system.user",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="User_Project_Like",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="PLCS_system.project",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="PLCS_system.user",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="User_Project_Collab",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("collab_request_msg", models.TextField(default="")),
                ("status", models.IntegerField(default=1)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="PLCS_system.project",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="PLCS_system.user",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="User_Permission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "permission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="PLCS_system.permission",
                    ),
                ),
                (
                    "user_p",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="PLCS_system.user",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Summary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file_name", models.CharField(default="", max_length=45)),
                ("file_description", models.TextField(default="")),
                ("file_link", models.CharField(default="", max_length=100)),
                (
                    "module_topic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="PLCS_system.module_topic",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="PLCS_system.user",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Role_Permission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "permission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="PLCS_system.permission",
                    ),
                ),
                (
                    "role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="PLCS_system.role",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="project",
            name="user_project",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="PLCS_system.user",
            ),
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("notification_title", models.CharField(default="", max_length=50)),
                ("notification_content", models.TextField(default="")),
                ("notification_type", models.CharField(default="", max_length=50)),
                ("notification_status", models.IntegerField(default=1)),
                ("notification_link_to", models.CharField(default="", max_length=50)),
                (
                    "notification_date",
                    models.DateTimeField(
                        default=datetime.datetime(2023, 6, 25, 18, 24, 48, 224758)
                    ),
                ),
                ("project_applied_to", models.CharField(default="", max_length=50)),
                (
                    "notification_recipient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="PLCS_system.user",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="learning_module",
            name="module_creator",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="PLCS_system.user"
            ),
        ),
        migrations.CreateModel(
            name="Collab_Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("task_x", models.CharField(default="", max_length=150)),
                ("task_deadline", models.DateField(null=True)),
                ("task_deliverables", models.TextField(default="")),
                ("task_status", models.IntegerField(default=0)),
                ("op_status", models.IntegerField(default=0)),
                (
                    "assigned_to",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="PLCS_system.user",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="PLCS_system.project",
                    ),
                ),
            ],
        ),
    ]
