# Generated by Django 4.1.1 on 2023-02-28 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uid", models.CharField(max_length=20)),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=15)),
                ("email", models.CharField(max_length=15)),
                ("password", models.CharField(max_length=15)),
            ],
            options={"db_table": "User",},
        ),
    ]
