# Generated by Django 4.1.1 on 2023-02-28 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("PLCS_system", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="user", name="uid",),
    ]
