# Generated by Django 4.1.1 on 2023-03-18 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("PLCS_system", "0002_remove_user_uid"),
    ]

    operations = [
        migrations.AddField(
            model_name="user", name="status", field=models.IntegerField(default=1),
        ),
    ]
