# Generated by Django 4.1.1 on 2023-07-01 10:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("PLCS_system", "0002_alter_learning_module_module_dor_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="project_tasks",
            field=models.TextField(default=""),
        ),
        migrations.AlterField(
            model_name="learning_module",
            name="module_DOR",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 7, 1, 13, 53, 24, 931968)
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="notification_date",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 7, 1, 13, 53, 24, 932967)
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="last_updated",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 7, 1, 13, 53, 24, 926973)
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="project_DOR",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 7, 1, 13, 53, 24, 926973)
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="project_deadline",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 7, 1, 13, 53, 24, 926973)
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="date_of_registration",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 7, 1, 13, 53, 24, 924974)
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="last_login",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 7, 1, 13, 53, 24, 924974)
            ),
        ),
    ]
