# Generated by Django 4.1.1 on 2023-03-18 14:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("PLCS_system", "0003_user_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="date_of_registration",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 3, 18, 17, 33, 53, 407338)
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="last_login",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 3, 18, 17, 33, 53, 407338)
            ),
        ),
    ]
