# Generated by Django 4.1.1 on 2023-03-18 14:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("PLCS_system", "0004_user_date_of_registration_user_last_login"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="date_of_registration",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 3, 18, 17, 48, 10, 278813)
            ),
        ),
        migrations.AlterField(
            model_name="user", name="email", field=models.CharField(max_length=45),
        ),
        migrations.AlterField(
            model_name="user", name="first_name", field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name="user",
            name="last_login",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 3, 18, 17, 48, 10, 278813)
            ),
        ),
    ]
