# Generated by Django 4.1.1 on 2023-03-18 20:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("PLCS_system", "0006_alter_user_date_of_registration_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="date_of_registration",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 3, 18, 23, 48, 3, 182408)
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="last_login",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 3, 18, 23, 48, 3, 182408)
            ),
        ),
    ]
