# Generated by Django 4.1.1 on 2023-04-01 19:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("PLCS_system", "0007_alter_user_date_of_registration_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("project_id", models.CharField(max_length=15)),
                ("project_title", models.CharField(max_length=300)),
                ("project_description", models.TextField()),
                (
                    "project_DOR",
                    models.DateTimeField(
                        default=datetime.datetime(2023, 4, 1, 22, 43, 59, 933096)
                    ),
                ),
                ("status", models.IntegerField(default=1)),
            ],
        ),
        migrations.AlterField(
            model_name="user",
            name="date_of_registration",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 4, 1, 22, 43, 59, 932096)
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="last_login",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 4, 1, 22, 43, 59, 932096)
            ),
        ),
    ]
