# Generated by Django 4.1.1 on 2023-07-01 11:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("PLCS_system", "0008_alter_learning_module_module_dor_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="learning_module",
            name="module_DOR",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 7, 1, 14, 18, 46, 331958)
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="notification_date",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 7, 1, 14, 18, 46, 331958)
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="last_updated",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 7, 1, 14, 18, 46, 331958)
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="project_DOR",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 7, 1, 14, 18, 46, 331958)
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="project_deadline",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 7, 1, 14, 18, 46, 331958)
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="date_of_registration",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 7, 1, 14, 18, 46, 316333)
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="last_login",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 7, 1, 14, 18, 46, 316333)
            ),
        ),
    ]
