# Generated by Django 4.1.1 on 2023-04-02 17:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "PLCS_system",
            "0009_alter_project_project_dor_alter_project_project_id_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="project_DOR",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 4, 2, 20, 3, 6, 832094)
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="date_of_registration",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 4, 2, 20, 3, 6, 832094)
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="last_login",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 4, 2, 20, 3, 6, 832094)
            ),
        ),
    ]
