# Generated by Django 4.1.1 on 2023-04-03 09:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("PLCS_system", "0010_alter_project_project_dor_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="project_DOR",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 4, 3, 12, 34, 41, 702638)
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="date_of_registration",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 4, 3, 12, 34, 41, 702638)
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="last_login",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 4, 3, 12, 34, 41, 702638)
            ),
        ),
    ]
