# Generated by Django 4.1.1 on 2023-04-08 21:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("PLCS_system", "0012_permissions_project_last_updated_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="permissions",
            name="project_DOR",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 4, 9, 0, 36, 56, 698230)
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="last_updated",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 4, 9, 0, 36, 56, 698230)
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="project_DOR",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 4, 9, 0, 36, 56, 698230)
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="date_of_registration",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 4, 9, 0, 36, 56, 697225)
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="last_login",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 4, 9, 0, 36, 56, 697225)
            ),
        ),
    ]
