# Generated by Django 4.1.1 on 2023-04-08 21:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("PLCS_system", "0013_alter_permissions_project_dor_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Permission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("project_id", models.CharField(default="PLC/", max_length=15)),
                ("project_title", models.CharField(max_length=300)),
                ("project_description", models.TextField()),
                (
                    "project_DOR",
                    models.DateTimeField(
                        default=datetime.datetime(2023, 4, 9, 0, 37, 32, 8095)
                    ),
                ),
                ("status", models.IntegerField(default=1)),
            ],
        ),
        migrations.DeleteModel(name="Permissions",),
        migrations.AlterField(
            model_name="project",
            name="last_updated",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 4, 9, 0, 37, 32, 8095)
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="project_DOR",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 4, 9, 0, 37, 32, 8095)
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="date_of_registration",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 4, 9, 0, 37, 32, 8095)
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="last_login",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 4, 9, 0, 37, 32, 8095)
            ),
        ),
    ]
