# Generated by Django 4.1.1 on 2023-04-10 21:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("PLCS_system", "0014_permission_delete_permissions_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Role",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("role_name", models.CharField(default="normal user", max_length=15)),
            ],
        ),
        migrations.AlterField(
            model_name="permission",
            name="project_DOR",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 4, 11, 0, 41, 30, 514216)
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="last_updated",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 4, 11, 0, 41, 30, 498591)
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="project_DOR",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 4, 11, 0, 41, 30, 498591)
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="date_of_registration",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 4, 11, 0, 41, 30, 498591)
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="last_login",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 4, 11, 0, 41, 30, 498591)
            ),
        ),
    ]
