# Generated by Django 4.1.1 on 2023-07-09 09:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("PLCS_system", "0014_alter_learning_module_module_dor_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="learning_module",
            name="module_ID",
            field=models.CharField(default="", max_length=50),
        ),
        migrations.AlterField(
            model_name="learning_module",
            name="module_DOR",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 7, 9, 12, 24, 47, 37424)
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="notification_date",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 7, 9, 12, 24, 47, 38422)
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="last_updated",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 7, 9, 12, 24, 47, 32428)
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="project_DOR",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 7, 9, 12, 24, 47, 32428)
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="date_of_registration",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 7, 9, 12, 24, 47, 30430)
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="last_login",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 7, 9, 12, 24, 47, 30430)
            ),
        ),
    ]
