# Generated by Django 4.1.1 on 2023-04-10 22:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("PLCS_system", "0015_role_alter_permission_project_dor_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="role",
            name="role_description",
            field=models.CharField(default="normal user", max_length=150),
        ),
        migrations.AlterField(
            model_name="permission",
            name="project_DOR",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 4, 11, 1, 3, 16, 41044)
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="last_updated",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 4, 11, 1, 3, 16, 41044)
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="project_DOR",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 4, 11, 1, 3, 16, 41044)
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="date_of_registration",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 4, 11, 1, 3, 16, 41044)
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="last_login",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 4, 11, 1, 3, 16, 41044)
            ),
        ),
    ]
