# Generated by Django 4.1.1 on 2023-04-22 22:18

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("PLCS_system", "0017_alter_permission_project_dor_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="permission",
            name="project_DOR",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 4, 23, 1, 18, 47, 928903)
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="last_updated",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 4, 23, 1, 18, 47, 928903)
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="project_DOR",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 4, 23, 1, 18, 47, 928903)
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="date_of_registration",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 4, 23, 1, 18, 47, 928903)
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="last_login",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 4, 23, 1, 18, 47, 928903)
            ),
        ),
        migrations.CreateModel(
            name="User_Permission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "permission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="PLCS_system.permission",
                    ),
                ),
                (
                    "user_p",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="PLCS_system.user",
                    ),
                ),
            ],
        ),
    ]
