# Generated by Django 4.1.1 on 2023-07-11 06:43

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("PLCS_system", "0018_collab_task_deliverables_from_user_feedback_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="learning_module",
            name="module_DOR",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 7, 11, 9, 43, 0, 347081)
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="notification_date",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 7, 11, 9, 43, 0, 347081)
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="last_updated",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 7, 11, 9, 43, 0, 347081)
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="project_DOR",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 7, 11, 9, 43, 0, 347081)
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="date_of_registration",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 7, 11, 9, 43, 0, 347081)
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="last_login",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 7, 11, 9, 43, 0, 347081)
            ),
        ),
        migrations.CreateModel(
            name="Topic_Flashcards",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("flashcard_question", models.TextField(default="")),
                ("flashcard_answer", models.TextField(default="")),
                (
                    "flashcards_belongs_to",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="PLCS_system.module_topic",
                    ),
                ),
            ],
        ),
    ]
