# Generated by Django 4.1.1 on 2023-04-23 14:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("PLCS_system", "0018_alter_permission_project_dor_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="permission", name="project_DOR",),
        migrations.RemoveField(model_name="permission", name="project_description",),
        migrations.RemoveField(model_name="permission", name="project_id",),
        migrations.RemoveField(model_name="permission", name="project_title",),
        migrations.RemoveField(model_name="permission", name="status",),
        migrations.AddField(
            model_name="permission",
            name="permission_action",
            field=models.CharField(default="", max_length=15),
        ),
        migrations.AlterField(
            model_name="project",
            name="last_updated",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 4, 23, 17, 52, 10, 847868)
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="project_DOR",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 4, 23, 17, 52, 10, 847868)
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="date_of_registration",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 4, 23, 17, 52, 10, 847868)
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="last_login",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 4, 23, 17, 52, 10, 847868)
            ),
        ),
    ]
