# Generated by Django 4.1.1 on 2023-04-23 22:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "PLCS_system",
            "0020_alter_project_last_updated_alter_project_project_dor_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="user_role", old_name="role", new_name="role_x",
        ),
        migrations.AlterField(
            model_name="project",
            name="last_updated",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 4, 24, 1, 19, 59, 287439)
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="project_DOR",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 4, 24, 1, 19, 59, 287439)
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="date_of_registration",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 4, 24, 1, 19, 59, 287439)
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="last_login",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 4, 24, 1, 19, 59, 287439)
            ),
        ),
    ]
