# Generated by Django 4.1.1 on 2023-04-26 13:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("PLCS_system", "0021_rename_role_user_role_role_x_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="last_updated",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 4, 26, 16, 21, 4, 476339)
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="project_DOR",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 4, 26, 16, 21, 4, 476339)
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="project_id",
            field=models.CharField(default="PLCS/", max_length=15),
        ),
        migrations.AlterField(
            model_name="user",
            name="date_of_registration",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 4, 26, 16, 21, 4, 476339)
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="last_login",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 4, 26, 16, 21, 4, 476339)
            ),
        ),
    ]
