# Generated by Django 4.1.1 on 2023-04-26 13:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "PLCS_system",
            "0022_alter_project_last_updated_alter_project_project_dor_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="project_budget",
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name="project",
            name="project_collaborators",
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name="project",
            name="project_deadline",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 4, 26, 16, 25, 12, 702376)
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="last_updated",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 4, 26, 16, 25, 12, 702376)
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="project_DOR",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 4, 26, 16, 25, 12, 702376)
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="date_of_registration",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 4, 26, 16, 25, 12, 702376)
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="last_login",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 4, 26, 16, 25, 12, 702376)
            ),
        ),
    ]
