# Generated by Django 4.1.1 on 2023-04-26 13:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "PLCS_system",
            "0023_project_project_budget_project_project_collaborators_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="project_files",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="project",
            name="project_images",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="project",
            name="project_skills",
            field=models.TextField(default=""),
        ),
        migrations.AlterField(
            model_name="project",
            name="last_updated",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 4, 26, 16, 35, 19, 169636)
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="project_DOR",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 4, 26, 16, 35, 19, 169636)
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="project_deadline",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 4, 26, 16, 35, 19, 169636)
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="date_of_registration",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 4, 26, 16, 35, 19, 169636)
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="last_login",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 4, 26, 16, 35, 19, 169636)
            ),
        ),
    ]
