# Generated by Django 4.1.1 on 2023-04-26 14:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "PLCS_system",
            "0028_alter_project_last_updated_alter_project_project_dor_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="last_updated",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 4, 26, 17, 10, 52, 390484)
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="project_DOR",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 4, 26, 17, 10, 52, 390484)
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="project_deadline",
            field=models.DateTimeField(default=""),
        ),
        migrations.AlterField(
            model_name="user",
            name="date_of_registration",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 4, 26, 17, 10, 52, 390484)
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="last_login",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 4, 26, 17, 10, 52, 390484)
            ),
        ),
    ]
