# Generated by Django 4.1.1 on 2023-04-27 02:12

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "PLCS_system",
            "0032_alter_project_last_updated_alter_project_project_dor_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="last_updated",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 4, 27, 5, 12, 28, 344454)
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="project_DOR",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 4, 27, 5, 12, 28, 344454)
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="user_project",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="PLCS_system.user",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="date_of_registration",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 4, 27, 5, 12, 28, 344454)
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="last_login",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 4, 27, 5, 12, 28, 344454)
            ),
        ),
    ]
