# Generated by Django 4.1.1 on 2023-05-14 08:58

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("PLCS_system", "0037_alter_permission_permission_action_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="last_updated",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 5, 14, 11, 58, 29, 320877)
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="project_DOR",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 5, 14, 11, 58, 29, 320877)
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="date_of_registration",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 5, 14, 11, 58, 29, 320877)
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="last_login",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 5, 14, 11, 58, 29, 320877)
            ),
        ),
        migrations.CreateModel(
            name="Learning_Module",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("module_title", models.CharField(default="", max_length=50)),
                ("module_description", models.TextField(default="")),
                ("module_tags", models.TextField(default="")),
                (
                    "module_DOR",
                    models.DateTimeField(
                        default=datetime.datetime(2023, 5, 14, 11, 58, 29, 336503)
                    ),
                ),
                (
                    "module_creator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="PLCS_system.user",
                    ),
                ),
            ],
        ),
    ]
