# Generated by Django 4.1.1 on 2023-05-19 22:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("PLCS_system", "0039_alter_learning_module_module_dor_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="learning_module",
            name="module_DOR",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 5, 20, 1, 26, 15, 141314)
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="notification_date",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 5, 20, 1, 26, 15, 141314)
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="last_updated",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 5, 20, 1, 26, 15, 138386)
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="project_DOR",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 5, 20, 1, 26, 15, 138386)
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="date_of_registration",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 5, 20, 1, 26, 15, 137410)
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="last_login",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 5, 20, 1, 26, 15, 137410)
            ),
        ),
    ]
