# Generated by Django 4.1.1 on 2023-05-22 15:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("PLCS_system", "0047_alter_learning_module_module_dor_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="notification_type",
            field=models.CharField(default="", max_length=50),
        ),
        migrations.AlterField(
            model_name="learning_module",
            name="module_DOR",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 5, 22, 18, 56, 30, 165939)
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="notification_date",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 5, 22, 18, 56, 30, 165939)
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="last_updated",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 5, 22, 18, 56, 30, 163009)
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="project_DOR",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 5, 22, 18, 56, 30, 163009)
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="date_of_registration",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 5, 22, 18, 56, 30, 162034)
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="last_login",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 5, 22, 18, 56, 30, 163009)
            ),
        ),
    ]
