# Generated by Django 4.1.1 on 2023-05-24 17:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("PLCS_system", "0048_notification_notification_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user", name="profile_img", field=models.TextField(default=""),
        ),
        migrations.AlterField(
            model_name="learning_module",
            name="module_DOR",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 5, 24, 20, 34, 39, 155203)
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="notification_date",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 5, 24, 20, 34, 39, 156179)
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="last_updated",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 5, 24, 20, 34, 39, 151298)
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="project_DOR",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 5, 24, 20, 34, 39, 151298)
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="date_of_registration",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 5, 24, 20, 34, 39, 151298)
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="last_login",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 5, 24, 20, 34, 39, 151298)
            ),
        ),
    ]
