# Generated by Django 4.1.1 on 2023-05-27 10:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "PLCS_system",
            "0049_user_profile_img_alter_learning_module_module_dor_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="learning_interests",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="user",
            name="project_interests",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="user",
            name="user_activity_tags",
            field=models.TextField(default=""),
        ),
        migrations.AlterField(
            model_name="learning_module",
            name="module_DOR",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 5, 27, 13, 48, 9, 346523)
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="notification_date",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 5, 27, 13, 48, 9, 346523)
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="last_updated",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 5, 27, 13, 48, 9, 343595)
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="project_DOR",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 5, 27, 13, 48, 9, 343595)
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="date_of_registration",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 5, 27, 13, 48, 9, 342619)
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="last_login",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 5, 27, 13, 48, 9, 342619)
            ),
        ),
    ]
