# Generated by Django 4.1.1 on 2023-06-01 13:18

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("PLCS_system", "0058_alter_learning_module_module_dor_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="collab_task",
            name="assigned_to",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                to="PLCS_system.user",
            ),
        ),
        migrations.AlterField(
            model_name="learning_module",
            name="module_DOR",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 6, 1, 16, 18, 13, 800695)
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="notification_date",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 6, 1, 16, 18, 13, 801695)
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="last_updated",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 6, 1, 16, 18, 13, 795702)
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="project_DOR",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 6, 1, 16, 18, 13, 794700)
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="date_of_registration",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 6, 1, 16, 18, 13, 793701)
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="last_login",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 6, 1, 16, 18, 13, 793701)
            ),
        ),
    ]
