# Generated by Django 4.1.1 on 2023-06-01 14:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("PLCS_system", "0063_alter_learning_module_module_dor_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="collab_task", name="task_deadline",),
        migrations.AlterField(
            model_name="learning_module",
            name="module_DOR",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 6, 1, 17, 42, 32, 116557)
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="notification_date",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 6, 1, 17, 42, 32, 116557)
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="last_updated",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 6, 1, 17, 42, 32, 116557)
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="project_DOR",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 6, 1, 17, 42, 32, 116557)
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="date_of_registration",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 6, 1, 17, 42, 32, 116557)
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="last_login",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 6, 1, 17, 42, 32, 116557)
            ),
        ),
    ]
